name: Setup Nix
description: Install Nix and restore cache

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
    - uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
