name: Setup Nix
description: Install Nix and restore cache

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v31
    - uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
